"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"
[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on   = [ "<C-n>" ]
run = '''
	shell 'dragon -x -i -T "$1"' --confirm
'''
