# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = true
linemode       = "size_and_mtime"
show_hidden    = false
show_symlink   = true
mouse_events   = [ "click", "scroll", "touch", "move", "drag"]
title_format   = "Yazi: {cwd}"

[preview]
image_filter    = "triangle"
image_quality   = 75

[opener]
edit = [
	{ run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]
open = [
  { run = 'sh ~/.local/share/bin/swwwallpaper.sh -s "$@"', desc = "Set Video Wallpaper", for = "linux", orphan = true },
  { run = 'wallpaper.sh -s "$@"', desc = "Set Wallpaper", for = "linux", orphan = true },
]
play = [
  { run = 'videocut "$@"', orphan = true, for = "unix" },
  { run = 'sh ~/.local/share/bin/set_video_wallpaper.sh "$@"', desc = "Wallpaper", orphan = true, for = "unix" },
]

[input]
# cd
cd_offset = [0, 18, 50, 3]

# create
create_offset = [0, 18, 50, 3]

# trash
trash_offset = [0, 18, 50, 3]

# delete
delete_offset = [0, 18, 50, 3]

# filter
filter_offset = [0, 18, 50, 3]

# find
find_offset = [0, 18, 50, 3]

# search
search_offset = [0, 18, 50, 3]

# shell
shell_offset = [0, 18, 50, 3]

# overwrite
overwrite_offset = [0, 18, 50, 3]

# quit
quit_offset = [0, 18, 50, 3]

